# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de5d602ef680903fb7eb4203b9b8cefd52f6cbe9d396df9a2f8001efeb87cacd6f34f9030ecd6d78d58b27307efc494749dae219c5b4283e428f042d0d5a73ff

test:
  secret_key_base: 0a57531da5f9eba8e5c8315dfe94c1393ca8b951d7ba75abb2dd19ac07a1145441d32031f1215fc0bee3e3d0ebdd40f9e1b36145ed04135e0462a1259ae5edfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
